version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: employees
      POSTGRES_PASSWORD: employees
  employees:
    image: employees
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/employees'
