GET http://localhost:8081/api/employees
Accept: application/json

###

GET http://localhost:8081/api/employees/300
Accept: application/json


### Create employee

POST http://localhost:8081/api/employees
Content-Type: application/json
Accept: application/json

{
  "name": "Jane Doe",
  "eid": -1
}

### Update

PUT http://localhost:8081/api/employees/9
Content-Type: application/json

{
  "name": "Jane Doe 2"
}

### Delete

DELETE http://localhost:8081/api/employees/9

### Create activity
POST http://localhost:8081/api/employees/6/activities
Content-Type: application/json
Accept: application/json

{
  "type": "Java",
  "date": "2022-01-12",
  "hour": 1
}

### Summary
GET http://localhost:8081/api/employees/2/activities/summary/2022-01
Content-Type: application/json
